apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp
          image: kv1995/testapp:v1
          ports:
             - containerPort: 8080
