apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-10-29T07:08:21Z
  labels:
    run: test
  name: test
  namespace: default
  resourceVersion: "11794"
  selfLink: /api/v1/namespaces/default/services/test
  uid: 6b2a8958-db49-11e8-a5cc-067091cab57a
spec:
  clusterIP: 10.107.116.162
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30902
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: test
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
